### ISSUE TITLE
No enum constant com.puppycrawl.tools.checkstyle.checks.blocks.BlockOption.STMT

### ISSUE THREAD

**Issue by CdeSaintRoman** [checkstyle/sonar-checkstyle#142]
Sonar version: 6.5 (build 27846)
Checkstyle sonar plugin version: 4.7

Steps to reproduce or description of problem:
Run Sonar Analysis.

Since I upgrade Checkstyle Sonar plugin to 4.7, I have the following error:
```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Can not execute Checkstyle
[...]
Caused by: java.lang.IllegalArgumentException: unable to parse stmt
	at com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck.setOption(EmptyBlockCheck.java:95)
	... 46 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.puppycrawl.tools.checkstyle.checks.blocks.BlockOption.STMT
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.puppycrawl.tools.checkstyle.checks.blocks.BlockOption.valueOf(BlockOption.java:27)
	at com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck.setOption(EmptyBlockCheck.java:92)
	... 46 more
```
Since the constant was modified in last version of Checkstyle, I suppose it's the reason?

**Comment by romani** [comment]
constant was changed at https://github.com/checkstyle/checkstyle/commit/fdb2140878cd476d8e71ed3a4e483baa30c98348#diff-b3eefca57e5c389b1ded478fa1f669d7

so , even 4.0 version should be affected.
Do you update from 3.X ?

**Comment by CdeSaintRoman** [comment]
Yes. So I'll see to rollback to a 3.X version of the plugin until the correction is effective.

**Comment by romani** [comment]
you do not need to rollback, just change the rule in Sonar to give it required value.

**Comment by CdeSaintRoman** [comment]
Sorry, I didn't read until the end your response. Thank you for your help.
