### ISSUE TITLE
Error running SonarQube analysis with Gradle - failing in Checkstyle

### ISSUE THREAD

**Issue by hirowla** [checkstyle/sonar-checkstyle#143]
Sonar version: 7.0 (also fails in 6.7.1)
Checkstyle sonar plugin verson: 4.8 (also fails in 4.7)
Gradle sonar plugin version: 2.6.1 (also fails in 2.6.2)

Steps to reproduce or description of problem:

Running a basic "gradle sonarqube" command I get the following output below. I was referred here from the sonarqube team (https://groups.google.com/forum/#!topic/sonarqube/fOU5raW1wCw).

Let me know if you need any more information.

--------------

When using "--info":

Task :sonarqube
Java Main Files AST scan (done) | time=5069ms
Java Test Files AST scan
0 source files to be analyzed
Java Test Files AST scan (done) | time=1ms
Sensor JavaSquidSensor [java] (done) | time=5612ms
Sensor PmdSensor [pmd]
Execute PMD 5.4.2...
Java version: 1.8
PMD configuration: C:\Work\IntelliJ\project\build\sonar\com.project_project_endor-api-common\pmd.xml
Execute PMD 5.4.2 done: 1285 ms
Sensor PmdSensor [pmd] (done) | time=1409ms
Sensor CheckstyleSensor [checkstyle]
Execute Checkstyle 8.8...
Checkstyle configuration: C:\Work\IntelliJ\project\build\sonar\com.project_project_endor-api-common\checkstyle.xml
Checkstyle charset: windows-1252

:sonarqube (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 21.047 secs.

FAILURE: Build failed with an exception.

-------------------------

Using a --stacktrace option I get the the following:

Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sonarqube'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Can not execute Checkstyle
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:109)
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:75)
        at org.sonar.plugins.checkstyle.CheckstyleSensor.analyse(CheckstyleSensor.java:59)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:281)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) 
        at com.sun.proxy.$Proxy151.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:99)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:142)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:135)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:122)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:762)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:729)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 28 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Cannot set property 'option' to 'stmt' in module Empty
Block
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:464)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:102)
        ... 69 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set property 'option' to 'stmt' in module EmptyBlock
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:238)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:190)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:170)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:459)
        ... 71 more
Caused by: java.lang.reflect.InvocationTargetException
        at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2127)
        at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2108)
        at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:437)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:228)
        ... 75 more
Caused by: java.lang.IllegalArgumentException: unable to parse stmt
        at com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck.setOption(EmptyBlockCheck.java:95)
        ... 79 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.puppycrawl.tools.checkstyle.checks.blocks.BlockOption.STMT
        at com.puppycrawl.tools.checkstyle.checks.blocks.BlockOption.valueOf(BlockOption.java:27)
        at com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck.setOption(EmptyBlockCheck.java:92)
        ... 79 more

**Comment by rnveach** [comment]
> Checkstyle sonar plugin verson: 4.8 (also fails in 4.7)

> Caused by: java.lang.IllegalArgumentException: unable to parse stmt
at com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck.setOption(EmptyBlockCheck.java:95)
> Caused by: java.lang.IllegalArgumentException: No enum constant com.puppycrawl.tools.checkstyle.checks.blocks.BlockOption.STMT

https://github.com/checkstyle/sonar-checkstyle/blob/ac9390445e91f185b00573893c72bfce2b4a60f5/checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L466-L471

We changed the option for the rule from `STMT` to `STATEMENT` in Checkstyle 8, https://github.com/checkstyle/sonar-checkstyle/issues/117.
Did you try deleting the rule and recreating it?

**Comment by aepfli** [comment]
we had the same issue, and exactly as @rnveach described, we did not use the default option in the EmptyBlockCheck, but provided our own, and we had to replace STMT with STATEMENT -> after that everything worked again.

But this change is due to a change in Checkstyle, and has nothing to do with this plugin directly.

**Comment by rnveach** [comment]
@aepfli Thanks for the confirmation. I will close this issue.

> has nothing to do with this plugin directly.

It depends on how you view it. Either this plugin or sonar should have someway to either reject old rules that are no longer valid or a way to force users to be upgraded. But no one on the team knows enough of sonar or it's API to know if this is even possible.
Until then, you have to manually recreate the rule when Checkstyle breaks compatibility.

**Comment by aepfli** [comment]
the rule is valid, it is just the configuration the user did... because you do not need to add those option as it is default -> and checkstyle explicitly has those changes in their release log. - i do not think that this is the plugin, because it clearly states to which version of checkstyle it upgrades, and based on that you have to evaluate your ruleset - if you use a checkstyle.xml locally it would have been the same. 

And i did not had to recreate the rule, it was just changing one field, and this was set by the user, as the default would have been handled.

![image](https://user-images.githubusercontent.com/9987394/36354578-e91b8cee-14d6-11e8-83d3-1b452ff25acf.png)

**Comment by aepfli** [comment]
nvm i misunderstood something :D
