### ISSUE TITLE
Auto-unboxing issue in CheckstyleAuditListener

### ISSUE THREAD

**Issue by tsjensen** [checkstyle/sonar-checkstyle#199]
Sonar version: 7.6
Checkstyle sonar plugin verson: 4.18

Steps to reproduce or description of problem:

Run any check which reports line 0 for an issue. This used to be the required behavior for checks that flag the entire file, and have no relation to the AST. For example FileSetChecks.  
I know there was a breaking change in checkstyle/checkstyle#6000, changing the "magic" line number to 1. This kind of neutralizes this problem.  
BUT: I noticed the problem running custom checks at work. I would expect some custom checks to be around that haven't noticed checkstyle/checkstyle#6000.

The error caused is this:
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\path\to\File.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:304)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:111)
        ... 71 more
Caused by: java.lang.NullPointerException
        at org.sonar.plugins.checkstyle.CheckstyleAuditListener.addError(CheckstyleAuditListener.java:106)
        at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:401)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:292)
        ... 73 more
```

I have already fixed this, it's a small thing. PR upcoming.

**Comment by rnveach** [comment]
Code is at https://github.com/checkstyle/sonar-checkstyle/blob/e16745294f6d0e8905bc8fc302a765e9b394ac78/checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleAuditListener.java#L106 which does indeed return a class Integer https://github.com/checkstyle/sonar-checkstyle/blob/e16745294f6d0e8905bc8fc302a765e9b394ac78/checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleAuditListener.java#L160

I'm not sure why code would rather use `null` instead of `0`. Seems odd.
https://github.com/checkstyle/sonar-checkstyle/blob/e16745294f6d0e8905bc8fc302a765e9b394ac78/checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleAuditListener.java#L164-L166

**Comment by rnveach** [comment]
> This used to be the required behavior for checks that flag the entire file

So why wasn't this an issue before but it is now?
