### ISSUE TITLE
AnnotationLocationCheck: Token "PARAMETER_DEF" was not found in Acceptable tokens list

### ISSUE THREAD

**Issue by muhlba91** [checkstyle/sonar-checkstyle#228]
Checkstyle sonar plugin verson: `4.21`

Steps to reproduce or description of problem:
After updating the Checkstyle plugin from `4.20` to `4.21` the `AnnotationLocationCheck` throws the following exception:

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "PARAMETER_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationLocationCheck
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:110)
        ... 151 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "PARAMETER_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationLocationCheck
        at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:231)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:141)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:472)
        ... 153 more
```

Previously, I have enabled the `AnnotationLocationCheck` using `PARAMETER_DEF` as a token.

**Comment by muhlba91** [comment]
In plugin version `4.21` Checkstyle has been updated to `8.21` which has removed the token `PARAMETER_DEF` from this check.

Please find the corresponding check in your SonarQube quality profile (search for `Annotation Location` in the `Checkstyle (Java)` repository) and remove `PARAMETER_DEF` from the `tokens` list.

**Comment by romani** [comment]
it is caused by https://github.com/checkstyle/checkstyle/issues/6462 , release in 8.21
declared as braking change - https://checkstyle.org/releasenotes.html#Release_8.21

**Comment by romani** [comment]
@muhlba91 , should we close this old issue?
