### ISSUE TITLE
Exception when scanning Java files

### ISSUE THREAD

**Issue by ramaprakashganesan** [checkstyle/sonar-checkstyle#285]
Sonarqube server version: 8.1
Checkstyle sonar plugin version: 4.27

Steps to reproduce or description of problem: 
We are trying to scan JDK 8 compatible product code using sonar scanner 4.2. This version of sonar-scanner uses Java 11. It threw exceptions and caused scan to fail as mentioned below. 

The same code was also scanned with sonar-scanner 3.3 that runs with Java 8, and similar exceptions were seen. 

Note - These errors did not seem to come earlier when using Checkstyle sonar plugin version 4.8 on Sonarqube server 6.7.1. That used to run fine with sonar-scanner 3.3 that runs with Java 8.

_17:02:35.144 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Can not execute Checkstyle
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:109)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:78)
	at org.sonar.plugins.checkstyle.CheckstyleSensor.execute(CheckstyleSensor.java:42)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
..
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\Jenkins\workspace\sonar_iam\IAM\modules\reconciliation\src\com\ca\reconciliation\syncagent\SyncAgentIplanet.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:303)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:102)
	... 32 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file C:\Jenkins\workspace\sonar_iam\IAM\modules\reconciliation\src\com\ca\reconciliation\syncagent\SyncAgentIplanet.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
..
	... 34 more
Caused by: java.lang.IllegalStateException: C:\Jenkins\workspace\sonar_iam\IAM\modules\reconciliation\src\com\ca\reconciliation\syncagent\SyncAgentIplanet.java:154:17: unexpected token: NamingEnumeration
	at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:93)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:411)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
..
	... 38 more
Caused by: C:\Jenkins\workspace\sonar_iam\IAM\modules\reconciliation\src\com\ca\reconciliation\syncagent\SyncAgentIplanet.java:154:17: unexpected token: NamingEnumeration
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.traditionalStatement(GeneratedJavaRecognizer.java:5506)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.statement(GeneratedJavaRecognizer.java:4276)
..
	... 40 more
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeeded?
ERROR: SonarQube scanner exited with non-zero code: 1_

**Comment by rnveach** [comment]
> Caused by: C:\Jenkins\workspace\sonar_iam\IAM\modules\reconciliation\src\com\ca\reconciliation\syncagent\SyncAgentIplanet.java:154:17: unexpected token: NamingEnumeration

It looks like the file in question is not being recognized as valid Java.

Can you provide the contents of the file and can reproduce the issue? You can slim it down as much as you need if it has sensitive information, we just need to be able to reproduce the issue.

**Comment by ramaprakashganesan** [comment]
[STAppletJDK12.zip](https://github.com/checkstyle/sonar-checkstyle/files/4169483/STAppletJDK12.zip)

**Comment by rnveach** [comment]
Here is the trimmed version:
````
$ cat TestClass.java
public class STAppletJDK12 {
    private void findMatches(String str) {
        Enumeration enum = null;
    }
}


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="EmptyBlock" />
    </module>
</module>

$ java -jar checkstyle-8.29-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:304)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:400)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file TestClass.java.
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
    ... 5 more
Caused by: java.lang.IllegalStateException: TestClass.java:3:9: unexpected token: Enumeration
    at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:93)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:411)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
    ... 9 more
Caused by: TestClass.java:3:9: unexpected token: Enumeration
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.traditionalStatement(GeneratedJavaRecognizer.java:5628)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.statement(GeneratedJavaRecognizer.java:4397)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compoundStatement(GeneratedJavaRecognizer.java:4063)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3453)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2643)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
    ... 11 more
Checkstyle ends with 1 errors.
````

**Comment by rnveach** [comment]
@ramaprakashganesan 
> Enumeration enum = null;

I don't think this is valid Java code. `enum` is key word in Java. Variables can't be named the same as a keyword.
If the word is changed from `enum` to something else, the parser passes.

**Comment by romani** [comment]
If `javac` is not passing over file, issue is invalid.
