### ISSUE TITLE
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module IllegalType - Property 'format' does not exist, please check the documentation

### ISSUE THREAD

**Issue by vhuynh4thalesgroup** [checkstyle/sonar-checkstyle#301]
Sonar version: 7.9LTS (scanner = gradle plugin 2.7)
Checkstyle sonar plugin version: 4.20

Steps to reproduce or description of problem:
Launch a SonarQube analyze with gradle scanner for sonarqube

```
12:12:27 Checkstyle configuration: /local2/localdata/tc/rgscisrv03SURV_new/workspace/_CDRF_CDRF_Composite_master-24FLMWT7FZ253J2HI6L7I65LTCS5GANF4OMT4PC4AAW3TAXXIYQA/build/sonar/com.thalesgroup.las_cdrf_comp_cdr_facade/checkstyle.xml
12:12:27 * What went wrong:
12:12:27 Execution failed for task ':sonarqube'.
12:12:27 > Can not execute Checkstyle
12:12:27 Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module IllegalType - Property 'format' does not exist, please check the documentation
12:12:27  at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:136)
12:12:27  at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
12:12:27  at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:472)
12:12:27  ... 121 more
12:12:27 Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'format' does not exist, please check the documentation
12:12:27  at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:223)12:12:27  at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:191)
12:12:27  at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:131)
12:12:27  ... 123 more
```
Any idea of what is wrong ?

**Comment by romani** [comment]
https://checkstyle.org/releasenotes.html#Release_8.18
> IllegalType: rename "format" property to "illegalAbstractClassNameFormat". Author: rnveach #5900

it was renamed.
you need to recreate Rule in Sonar UI.

**Comment by vhuynh4thalesgroup** [comment]
Which rule are we talkinf about ?

**Comment by romani** [comment]
IllegalType

**Comment by vhuynh4thalesgroup** [comment]
Yeah sorry, I found it out but add another rule Right Curly with the same kind of problem. Thanks for your help.
