### ISSUE TITLE
Can not execute Checkstyle - v8.35

### ISSUE THREAD

**Issue by mrmunch** [checkstyle/sonar-checkstyle#343]
Sonar version: 7.9.4
Checkstyle sonar plugin version: 8.35

I recently updated a very old Sonar instance, from v6.7.7 zo 7.9.4.
I also updated Checkstyle from v3.7 to v8.35.
Since that update, I get this error with the Checkstyle plugin:

```ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Can not execute Checkstyle
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:110)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:78)
	at org.sonar.plugins.checkstyle.CheckstyleSensor.execute(CheckstyleSensor.java:42)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:99)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: SuppressionCommentFilter is not allowed as a child in Checker
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:502)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:102)
	... 32 more
```
As I do not have much experience with SonarQube, any help would be appreciated.

**Comment by muhlba91** [comment]
Due to the changed way we create SQ information out of Checkstyle data, this became a known regression added. Filters (like the SuppressionCommentFilter you enabled in SQ) are not allowed to be set directly in SQ through rules. If you need to use such filters, please configure them globally in SQ settings.
We are working on a resolution to remove them from the list of available rules in SQ UI and other regressions introduced.

**Comment by romani** [comment]
@mrmunch , you can see screenshot at https://github.com/checkstyle/sonar-checkstyle/issues/55 to get ideas where to put Filters.

**Comment by mrmunch** [comment]
Hi @muhlba91 and @romani 
as I understand, I cannot remove these filters (inside the rules) on my own? So I have to wait until you fixed these rules?

**Comment by romani** [comment]
Please remove yourself

**Comment by sonata82** [comment]
This issue came up while updating SonarQube from 6.7 to 7.9. For anybody with the same issue: try opening the mentioned settings under `Administration -> Configuration -> General Settings -> Java` and reset both fields to the default value, even if that is the current displayed value.

**Comment by RubenMF99** [comment]
@sonata82 donde puedo acceder a esa ruta?
