### ISSUE TITLE
throw StackOverFlow exception SinglelineDetector#checkLine

### ISSUE THREAD

**Issue by gksxodnd007** [checkstyle/sonar-checkstyle#357]
Sonar version: `8.6.1`
Checkstyle sonar plugin version: `checkstyle-sonar-plugin-8.39`

Steps to reproduce or description of problem:

when i analysis java code using sonar-scanner-cli

```
java.lang.Error: Error was thrown while processing /home1/irteam/workspace/nsp_PR-1712/nsp_core/src/main/java/com/naver/pay/nsp/core/service/payment/method/card/SimplePayCardOwnerType.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:103)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:78)
	at org.sonar.plugins.checkstyle.CheckstyleSensor.execute(CheckstyleSensor.java:42)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:393)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:389)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.StackOverflowError
	at com.puppycrawl.tools.checkstyle.api.FileContents.hasIntersectionWithBlockComment(FileContents.java:285)
	at com.puppycrawl.tools.checkstyle.api.FileContents.hasIntersectionWithComment(FileContents.java:267)
	at com.puppycrawl.tools.checkstyle.checks.regexp.CommentSuppressor.shouldSuppress(CommentSuppressor.java:47)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:113)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
```

break out stack over flow error. i can't find solution. how can i fix it?

**Comment by muhlba91** [comment]
did you check the corresponding checks (comment suppressor and single line detector) with the CS command itself without SQ?

side note: SQ cli should create a checkstyle xml file temporarily which you can use to check. in gradle or maven it‘s the build directory; for the SQ cli i don‘t know where it is.

from the stacktrace it looks like it belong to the main CS repo and not the SQ integration. however, confirmation is needed for proper determination.

**Comment by gksxodnd007** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd"><!-- Generated by Sonar --><module name="Checker"><module name="SuppressWarningsFilter" /><module name="RegexpSingleline"><property name="id" value="no_trailing_spaces"/><property name="severity" value="warning"/><property name="format" value="^(?!\s+\* $).*?\s+$"/><property name="message" value="[no-trailing-spaces] Line has trailing spaces."/></module><module name="UniqueProperties"><property name="severity" value="warning"/><property name="fileExtensions" value="properties"/></module><module name="Translation"><property name="severity" value="info"/><property name="fileExtensions" value="properties"/><property name="baseName" value="^messages.*$"/></module><module name="NewlineAtEndOfFile"><property name="severity" value="info"/><property name="lineSeparator" value="lf"/></module><module name="Header"><property name="severity" value="warning"/></module><module name="FileLength"><property name="severity" value="warning"/></module><module name="RegexpHeader"><property name="severity" value="warning"/></module><module name="RegexpMultiline"><property name="id" value="newline_lf"/><property name="severity" value="warning"/><property name="format" value="\r\n"/><property name="message" value="[newline-lf] Line must end with LF, not CRLF"/></module><module name="TreeWalker"><module name="SuppressWarningsHolder"/> <module name="AbbreviationAsWordInName"><property name="severity" value="warning"/><property name="ignoreOverriddenMethods" value="true"/><property name="ignoreStatic" value="true"/><property name="tokens" value="CLASS_DEF,INTERFACE_DEF,ENUM_DEF,ANNOTATION_DEF,ANNOTATION_FIELD_DEF,PARAMETER_DEF,VARIABLE_DEF,METHOD_DEF"/><property name="ignoreFinal" value="false"/><property name="allowedAbbreviations" value="DAO,BO"/><property name="ignoreStaticFinal" value="true"/><property name="allowedAbbreviationLength" value="1"/></module><module name="AbstractClassName"><property name="severity" value="warning"/><property name="format" value="^Abstract.+$"/><property name="ignoreName" value="false"/><property name="ignoreModifier" value="false"/></module><module name="AnnotationUseStyle"><property name="severity" value="warning"/></module><module name="AnonInnerLength"><property name="severity" value="warning"/></module><module name="ArrayTrailingComma"><property name="severity" value="warning"/><property name="alwaysDemandTrailingComma" value="false"/></module><module name="ArrayTypeStyle"><property name="severity" value="info"/></module><module name="AtclauseOrder"><property name="severity" value="warning"/><property name="tagOrder" value="@author,@version,@param,@return,@throws,@exception,@see,@since,@serial,@serialField,@serialData,@deprecated"/></module><module name="AvoidEscapedUnicodeCharacters"><property name="severity" value="warning"/><property name="allowByTailComment" value="false"/><property name="allowIfAllCharactersEscaped" value="false"/><property name="allowEscapesForControlCharacters" value="false"/><property name="allowNonPrintableEscapes" value="false"/></module><module name="AvoidNestedBlocks"><property name="severity" value="warning"/></module><module name="AvoidStarImport"><property name="severity" value="info"/><property name="allowStaticMemberImports" value="true"/><property name="allowClassImports" value="false"/></module><module name="AvoidStaticImport"><property name="severity" value="info"/></module><module name="CatchParameterName"><property name="severity" value="warning"/><property name="format" value="^(e|t|ex|[a-z][a-z][a-zA-Z]+)$"/></module><module name="ClassDataAbstractionCoupling"><property name="severity" value="warning"/></module><module name="ClassFanOutComplexity"><property name="severity" value="warning"/></module><module name="ClassMemberImpliedModifier"><property name="severity" value="info"/><property name="violateImpliedStaticOnNestedEnum" value="true"/><property name="violateImpliedStaticOnNestedInterface" value="true"/></module><module name="ClassTypeParameterName"><property name="severity" value="warning"/><property name="format" value="^[A-Z]$"/></module><module name="CommentsIndentation"><property name="severity" value="info"/><property name="tokens" value="SINGLE_LINE_COMMENT,BLOCK_COMMENT_BEGIN"/></module><module name="CovariantEquals"><property name="severity" value="error"/></module><module name="CustomImportOrder"><property name="severity" value="warning"/><property name="thirdPartyPackageRegExp" value=".*"/><property name="separateLineBetweenGroups" value="true"/><property name="sortImportsInGroupAlphabetically" value="false"/><property name="specialImportsRegExp" value="^(com\.nhncorp|com\.navercorp|com\.naver)\."/><property name="customImportOrderRules" value="STATIC###STANDARD_JAVA_PACKAGE###THIRD_PARTY_PACKAGE###SPECIAL_IMPORTS"/><property name="standardPackageRegExp" value="java|javax"/></module><module name="CyclomaticComplexity"><property name="severity" value="warning"/><property name="tokens" value="LITERAL_WHILE,LITERAL_DO,LITERAL_FOR,LITERAL_IF,LITERAL_SWITCH,LITERAL_CASE,LITERAL_CATCH,QUESTION,LAND,LOR"/><property name="switchBlockAsSingleDecisionPoint" value="false"/><property name="max" value="10"/></module><module name="DefaultComesLast"><property name="severity" value="warning"/><property name="skipIfLastAndSharedWithCase" value="false"/></module><module name="DescendantToken"><property name="severity" value="info"/><property name="sumTokenCounts" value="false"/></module><module name="EmptyBlock"><property name="severity" value="warning"/><property name="tokens" value="LITERAL_WHILE,LITERAL_TRY,LITERAL_FINALLY,LITERAL_DO,LITERAL_IF,LITERAL_ELSE,LITERAL_FOR,INSTANCE_INIT,STATIC_INIT,LITERAL_SWITCH,LITERAL_SYNCHRONIZED"/><property name="option" value="statement"/></module><module name="EmptyCatchBlock"><property name="severity" value="warning"/><property name="exceptionVariableName" value="^$"/><property name="commentFormat" value=".*"/></module><module name="EmptyForInitializerPad"><property name="severity" value="info"/></module><module name="EmptyForIteratorPad"><property name="severity" value="info"/></module><module name="EmptyLineSeparator"><property name="id" value="blankline_between_methods"/><property name="severity" value="warning"/><property name="tokens" value="METHOD_DEF"/></module><module name="EmptyStatement"><property name="severity" value="info"/></module><module name="EqualsAvoidNull"><property name="severity" value="warning"/><property name="ignoreEqualsIgnoreCase" value="false"/></module><module name="EqualsHashCode"><property name="severity" value="error"/></module><module name="ExplicitInitialization"><property name="severity" value="warning"/></module><module name="FallThrough"><property name="severity" value="warning"/><property name="reliefPattern" value="falls?[ -]?thr(u|ough)"/><property name="checkLastCaseGroup" value="false"/></module><module name="FinalClass"><property name="severity" value="warning"/></module><module name="GenericWhitespace"><property name="severity" value="info"/></module><module name="HideUtilityClassConstructor"><property name="severity" value="warning"/></module><module name="IllegalCatch"><property name="severity" value="warning"/></module><module name="IllegalImport"><property name="severity" value="warning"/><property name="regexp" value="false"/></module><module name="IllegalInstantiation"><property name="severity" value="warning"/><property name="tokens" value="CLASS_DEF"/></module><module name="IllegalThrows"><property name="severity" value="warning"/><property name="ignoreOverriddenMethods" value="true"/></module><module name="IllegalTokenText"><property name="id" value="special_escape"/><property name="severity" value="warning"/><property name="format" value="\\u00(08|09|0(a|A)|0(c|C)|0(d|D)|22|27|5(C|c))|\\(0(10|11|12|14|15|42|47)|134)"/><property name="tokens" value="STRING_LITERAL,CHAR_LITERAL"/><property name="message" value="[array-square-after-type]  Avoid using corresponding octal or Unicode escape."/></module><module name="Indentation"><property name="severity" value="info"/><property name="throwsIndent" value="4"/><property name="tabWidth" value="4"/><property name="arrayInitIndent" value="4"/><property name="forceStrictCondition" value="false"/><property name="caseIndent" value="4"/><property name="basicOffset" value="4"/><property name="braceAdjustment" value="0"/><property name="lineWrappingIndentation" value="4"/></module><module name="InnerTypeLast"><property name="severity" value="info"/></module><module name="InterfaceIsType"><property name="severity" value="warning"/></module><module name="InterfaceMemberImpliedModifier"><property name="severity" value="info"/><property name="violateImpliedFinalField" value="true"/><property name="violateImpliedStaticNested" value="true"/><property name="violateImpliedAbstractMethod" value="true"/><property name="violateImpliedStaticField" value="true"/><property name="violateImpliedPublicNested" value="true"/><property name="violateImpliedPublicMethod" value="true"/><property name="violateImpliedPublicField" value="true"/></module><module name="InterfaceTypeParameterName"><property name="severity" value="warning"/><property name="format" value="^[A-Z]$"/></module><module name="JavaNCSS"><property name="severity" value="warning"/></module><module name="JavadocParagraph"><property name="severity" value="warning"/><property name="allowNewlineParagraph" value="true"/></module><module name="JavadocTagContinuationIndentation"><property name="severity" value="warning"/><property name="offset" value="4"/></module><module name="LambdaParameterName"><property name="severity" value="warning"/><property name="format" value="^[a-z][a-zA-Z0-9]*$"/></module><module name="LeftCurly"><property name="id" value="braces_knr_style_left"/><property name="severity" value="info"/></module><module name="LocalFinalVariableName"><property name="severity" value="warning"/><property name="format" value="^[a-z][a-zA-Z0-9]*$"/><property name="tokens" value="VARIABLE_DEF,PARAMETER_DEF,RESOURCE"/></module><module name="LocalVariableName"><property name="id" value="var_lower_camelcase"/><property name="severity" value="warning"/><property name="format" value="^[a-z][a-zA-Z0-9][a-zA-Z0-9]*$"/><property name="allowOneCharVarInForLoop" value="true"/></module><module name="MemberName"><property name="id" value="var_lower_camelcase_memberName"/><property name="severity" value="warning"/><property name="format" value="^[a-z][a-zA-Z0-9][a-zA-Z0-9]*$"/></module><module name="MethodCount"><property name="severity" value="warning"/><property name="maxTotal" value="100"/><property name="maxPrivate" value="100"/><property name="tokens" value="CLASS_DEF,ENUM_CONSTANT_DEF,ENUM_DEF,INTERFACE_DEF,ANNOTATION_DEF"/><property name="maxPackage" value="100"/><property name="maxProtected" value="100"/><property name="maxPublic" value="100"/></module><module name="MethodName"><property name="severity" value="warning"/><property name="allowClassName" value="false"/><property name="applyToPackage" value="true"/><property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9_]*$"/><property name="applyToPublic" value="true"/><property name="applyToPrivate" value="true"/><property name="applyToProtected" value="true"/></module><module name="MethodParamPad"><property name="id" value="no_space_between_identifier_parentheses"/><property name="severity" value="warning"/></module><module name="MethodTypeParameterName"><property name="severity" value="warning"/><property name="format" value="^[A-Z]$"/></module><module name="MissingDeprecated"><property name="severity" value="warning"/></module><module name="MissingOverride"><property name="severity" value="warning"/></module><module name="MissingSwitchDefault"><property name="severity" value="warning"/></module><module name="ModifiedControlVariable"><property name="severity" value="warning"/><property name="skipEnhancedForLoopVariable" value="false"/></module><module name="ModifierOrder"><property name="severity" value="info"/></module><module name="MultipleVariableDeclarations"><property name="severity" value="warning"/></module><module name="MutableException"><property name="severity" value="warning"/></module><module name="NPathComplexity"><property name="severity" value="warning"/></module><module name="NestedForDepth"><property name="severity" value="warning"/><property name="max" value="1"/></module><module name="NestedIfDepth"><property name="severity" value="warning"/></module><module name="NestedTryDepth"><property name="severity" value="warning"/></module><module name="NoClone"><property name="severity" value="warning"/></module><module name="NoFinalizer"><property name="severity" value="warning"/></module><module name="NoLineWrap"><property name="id" value="1_line_package_import"/><property name="severity" value="warning"/><property name="tokens" value="PACKAGE_DEF,IMPORT"/></module><module name="NoWhitespaceAfter"><property name="id" value="no_space_unary_operator_after"/><property name="severity" value="info"/><property name="tokens" value="INC,DEC,UNARY_MINUS,UNARY_PLUS,BNOT,LNOT"/></module><module name="NoWhitespaceBefore"><property name="id" value="no_space_unary_operator_before"/><property name="severity" value="info"/><property name="tokens" value="POST_INC,POST_DEC"/></module><module name="NoWhitespaceBefore"><property name="id" value="space_after_comma_semicolon_before"/><property name="severity" value="info"/><property name="tokens" value="COMMA,SEMI"/></module><module name="NonEmptyAtclauseDescription"><property name="severity" value="warning"/><property name="javadocTokens" value="PARAM_LITERAL,RETURN_LITERAL,THROWS_LITERAL,EXCEPTION_LITERAL,DEPRECATED_LITERAL"/></module><module name="OneStatementPerLine"><property name="severity" value="warning"/><property name="treatTryResourcesAsStatement" value="false"/></module><module name="OneTopLevelClass"><property name="severity" value="warning"/></module><module name="OperatorWrap"><property name="id" value="line_wrapping_position_nl"/><property name="severity" value="info"/><property name="tokens" value="BAND,BOR,BSR,BXOR,DIV,EQUAL,GE,GT,LAND,LE,LITERAL_INSTANCEOF,LOR,LT,MINUS,MOD,NOT_EQUAL,PLUS,QUESTION,SL,SR,STAR"/><property name="option" value="nl"/></module><module name="OuterTypeFilename"><property name="severity" value="warning"/></module><module name="OverloadMethodsDeclarationOrder"><property name="severity" value="warning"/></module><module name="PackageAnnotation"><property name="severity" value="info"/></module><module name="PackageName"><property name="severity" value="warning"/><property name="format" value="^[a-z]+(\.[a-z][a-z0-9]*)*$"/></module><module name="ParameterAssignment"><property name="severity" value="warning"/></module><module name="ParameterName"><property name="severity" value="warning"/><property name="format" value="^[a-z][a-zA-Z0-9][a-zA-Z0-9]*$"/><property name="ignoreOverridden" value="false"/><property name="accessModifiers" value="public,protected,package,private"/></module><module name="RedundantImport"><property name="severity" value="info"/></module><module name="RegexpSinglelineJava"><property name="id" value="indentation_tab"/><property name="severity" value="warning"/><property name="ignoreComments" value="true"/><property name="format" value="^\t*"/><property name="message" value="[indentation-tab] Indent must use tab characters"/></module><module name="RequireThis"><property name="severity" value="warning"/></module><module name="ReturnCount"><property name="severity" value="warning"/><property name="format" value="^equals$"/><property name="tokens" value="CTOR_DEF,METHOD_DEF,LAMBDA"/><property name="maxForVoid" value="1"/><property name="max" value="2"/></module><module name="RightCurly"><property name="id" value="braces_knr_style"/><property name="severity" value="info"/><property name="tokens" value="CLASS_DEF,METHOD_DEF,CTOR_DEF,LITERAL_FOR,LITERAL_WHILE,STATIC_INIT,INSTANCE_INIT"/><property name="option" value="alone"/></module><module name="RightCurly"><property name="id" value="sub_flow_after_brace"/><property name="severity" value="info"/><property name="tokens" value="LITERAL_TRY,LITERAL_CATCH,LITERAL_FINALLY,LITERAL_IF,LITERAL_ELSE,LITERAL_DO"/><property name="option" value="same"/></module><module name="SeparatorWrap"><property name="id" value="line_wrapping_position_SeparatorWrap_comma"/><property name="severity" value="info"/><property name="tokens" value="COMMA"/><property name="option" value="eol"/></module><module name="SeparatorWrap"><property name="id" value="line_wrapping_position_SeparatorWrap_dot"/><property name="severity" value="info"/><property name="tokens" value="DOT"/><property name="option" value="nl"/></module><module name="SimplifyBooleanExpression"><property name="severity" value="warning"/></module><module name="SimplifyBooleanReturn"><property name="severity" value="warning"/></module><module name="SingleLineJavadoc"><property name="severity" value="warning"/><property name="ignoreInlineTags" value="true"/></module><module name="SingleSpaceSeparator"><property name="severity" value="warning"/><property name="validateComments" value="false"/></module><module name="StringLiteralEquality"><property name="severity" value="error"/></module><module name="SuperClone"><property name="severity" value="warning"/></module><module name="SuperFinalize"><property name="severity" value="warning"/></module><module name="SuppressWarningsHolder"><property name="severity" value="info"/></module><module name="ThrowsCount"><property name="severity" value="warning"/><property name="max" value="4"/><property name="ignorePrivateMethods" value="true"/></module><module name="TypeName"><property name="id" value="class_interface_lower_camelcase"/><property name="severity" value="warning"/></module><module name="TypecastParenPad"><property name="id" value="no_space_typecasting"/><property name="severity" value="warning"/></module><module name="UnnecessaryParentheses"><property name="severity" value="info"/><property name="tokens" value="EXPR,IDENT,NUM_DOUBLE,NUM_FLOAT,NUM_INT,NUM_LONG,STRING_LITERAL,LITERAL_NULL,LITERAL_FALSE,LITERAL_TRUE,ASSIGN,BAND_ASSIGN,BOR_ASSIGN,BSR_ASSIGN,BXOR_ASSIGN,DIV_ASSIGN,MINUS_ASSIGN,MOD_ASSIGN,PLUS_ASSIGN,SL_ASSIGN,SR_ASSIGN,STAR_ASSIGN,LAMBDA"/></module><module name="UnusedImports"><property name="severity" value="info"/><property name="processJavadoc" value="true"/></module><module name="UpperEll"><property name="severity" value="info"/></module><module name="VariableDeclarationUsageDistance"><property name="severity" value="warning"/><property name="ignoreFinal" value="true"/><property name="allowedDistance" value="3"/><property name="validateBetweenScopes" value="false"/></module><module name="VisibilityModifier"><property name="severity" value="warning"/><property name="protectedAllowed" value="false"/><property name="immutableClassCanonicalNames" value="java.lang.String,java.lang.Integer,java.lang.Byte,java.lang.Character,java.lang.Short,java.lang.Boolean,java.lang.Long,java.lang.Double,java.lang.Float,java.lang.StackTraceElement,java.math.BigInteger,java.math.BigDecimal,java.io.File,java.util.Locale,java.util.UUID,java.net.URL,java.net.URI,java.net.Inet4Address,java.net.Inet6Address,java.net.InetSocketAddress"/><property name="publicMemberPattern" value="^serialVersionUID$"/><property name="packageAllowed" value="false"/><property name="allowPublicImmutableFields" value="true"/><property name="allowPublicFinalFields" value="false"/><property name="ignoreAnnotationCanonicalNames" value="org.junit.Rule,org.junit.ClassRule,com.google.common.annotations.VisibleForTesting"/></module><module name="WhitespaceAfter"><property name="id" value="space_after_comma_semicolon_after"/><property name="severity" value="info"/><property name="tokens" value="COMMA,SEMI"/></module><module name="WhitespaceAround"><property name="id" value="space_around_binary_ternary_operator_around"/><property name="severity" value="info"/><property name="tokens" value="ASSIGN, BAND, BAND_ASSIGN, BOR, BOR_ASSIGN, BSR, BSR_ASSIGN, BXOR, BXOR_ASSIGN, DIV,DIV_ASSIGN, EQUAL, GE, GT, LAND, LE, LOR, LT, MINUS, MINUS_ASSIGN, MOD, MOD_ASSIGN, NOT_EQUAL, PLUS, PLUS_ASSIGN, QUESTION, SL, SL_ASSIGN, SR, SR_ASSIGN, STAR, STAR_ASSIGN, TYPE_EXTENSION_AND"/></module><module name="WhitespaceAround"><property name="id" value="space_around_brace"/><property name="severity" value="info"/><property name="allowEmptyConstructors" value="true"/><property name="allowEmptyMethods" value="true"/><property name="allowEmptyLoops" value="true"/><property name="tokens" value="LCURLY, RCURLY, SLIST"/></module><module name="WhitespaceAround"><property name="id" value="space_around_colon_around"/><property name="severity" value="info"/><property name="ignoreEnhancedForColon" value="false"/><property name="tokens" value="COLON"/></module><module name="WhitespaceAround"><property name="id" value="space_between_keyword_parentheses"/><property name="severity" value="info"/><property name="tokens" value="DO_WHILE, LITERAL_ASSERT, LITERAL_CATCH, LITERAL_DO, LITERAL_ELSE, LITERAL_FINALLY, LITERAL_FOR, LITERAL_IF, LITERAL_RETURN,LITERAL_SWITCH, LITERAL_SYNCHRONIZED, LITERAL_TRY, LITERAL_WHILE"/></module><module name="SuppressionCommentFilter" /></module></module>
```
it is genereated by executing sonar scanner using maven sonar plugin. i can't find SinglelineDector

**Comment by muhlba91** [comment]
awesome, can you use this configuration with the CS command line tool on your code base to check if this runs through smoothly to triage if this is a bug of the SQ integration or CS itself? (https://checkstyle.org/cmdline.html, @romani might be able to help more regarding that)

this is the check in question:
```
<module name="RegexpSingleline">
<property name="id" value="no_trailing_spaces"/>
<property name="severity" value="warning"/>
<property name="format" value="^(?!\s+\* $).*?\s+$"/>
<property name="message" value="[no-trailing-spaces] Line has trailing spaces."/>
...
</module>
```

however, please use the entire xml file for the command line test to avoid side effects of different checks.

**Comment by gksxodnd007** [comment]
when i execute checkstype using command line, the result became successful like this
`java -jar ./checkstyle-8.40-all.jar -c ./checks.xml ./SimplePayCardOwnerType.java`

```
Starting audit...
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:1: Missing package-info.java file. [JavadocPackage]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:19:1: File contains tab characters (this is the first instance). [FileTabCharacter]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:19:9: Missing a Javadoc comment. [JavadocVariable]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:20:9: Missing a Javadoc comment. [JavadocVariable]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:21:9: Missing a Javadoc comment. [JavadocVariable]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:22:9: Missing a Javadoc comment. [JavadocVariable]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:24:9: Missing a Javadoc comment. [JavadocVariable]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:25:9: Missing a Javadoc comment. [JavadocVariable]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:27:32: Parameter code should be final. [FinalParameters]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:27:39: 'code' hides a field. [HiddenField]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:27:45: Parameter description should be final. [FinalParameters]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:27:52: 'description' hides a field. [HiddenField]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:32:9: Missing a Javadoc comment. [MissingJavadocMethod]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:37:9: Missing a Javadoc comment. [MissingJavadocMethod]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:41:9: Missing a Javadoc comment. [MissingJavadocMethod]
[ERROR] /Users/user/dev-tool/sonarqube-check/./SimplePayCardOwnerType.java:42:51: Parameter code should be final. [FinalParameters]
Audit done.
Checkstyle ends with 16 errors.
```

**Comment by gksxodnd007** [comment]
when i execute check style with command cli, the result is same like this
`java -jar ./checkstyle-8.40-all.jar -c ./checks.xml ./SimplePayCardOwnerType.java`
```
Starting audit...
Exception in thread "main" java.lang.Error: Error was thrown while processing ./SimplePayCardOwnerType.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.StackOverflowError
	at java.base/java.util.Collection.stream(Collection.java:711)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1693)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.puppycrawl.tools.checkstyle.api.FileContents.hasIntersectionWithBlockComment(FileContents.java:287)
	at com.puppycrawl.tools.checkstyle.api.FileContents.hasIntersectionWithComment(FileContents.java:267)
	at com.puppycrawl.tools.checkstyle.checks.regexp.CommentSuppressor.shouldSuppress(CommentSuppressor.java:47)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:113)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
        ...
```

**Comment by gksxodnd007** [comment]
i found something. if java class has a paragraph comment the checkstyle break out stackoverflow error.

like this
```java
/**
 *
 * @author aphros
 * @since 2019. 08. 06.
 */
```

**Comment by muhlba91** [comment]
thanks a lot for that finding! 👍 
this is definitely a bug in the main CS project and not of the SQ integration - can you please raise a bug ticket with the example you showed in https://github.com/checkstyle/checkstyle.

once that is solved and released, the usual release cycle will cover that in the SQ integration as well. :)

**Comment by gksxodnd007** [comment]
okay thanks. if check.xml import this module that property value like this.
```xml
<module name="RegexpSinglelineJava">
    <property name="severity" value="warning"/>
    <property name="ignoreComments" value="true"/>
    <property name="format" value="^\t* "/>
    <property name="message" value="[indentation-tab] Indent must use tab characters"/>
</module>
```
check style break out stackoverflow error when java file include multi line comment

**Comment by rnveach** [comment]
Resolution to fix module config at https://github.com/checkstyle/checkstyle/issues/9330#issuecomment-785916886 .

To me it seems like this issue can be closed as well.
