### ISSUE TITLE
Execution failed for task ':sonarqube'. > Can not execute Checkstyle

### ISSUE THREAD

**Issue by Sadashiv** [checkstyle/sonar-checkstyle#390]
Sonar version: 8.9
Checkstyle sonar plugin version: 4.29

./gradlew  sonarqube
Throws error with checkstyle issue
Caused by: **/home/user/folder1/src/main/java/org/SourceJobLogHandler.java.:32:47: expecting COLON, found ';'**

Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/user/folder1/src/main/java/org/SourceJobLogHandler.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:304)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:103)
        ... 260 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/user/folder1/src/main/java/org/SourceJobLogHandler.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
        ... 262 more
Caused by: java.lang.IllegalStateException: /home/user/folder1/src/main/java/org/SourceJobLogHandler.java.:32:47: expecting COLON, found ';'
        at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:93)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:411)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
        ... 266 more
Caused by: **/home/user/folder1/src/main/java/org/SourceJobLogHandler.java.:32:47: expecting COLON, found ';'**
        at antlr.Parser.match(Parser.java:211)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.aCase(GeneratedJavaRecognizer.java:6226)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.casesGroup(GeneratedJavaRecognizer.java:5760)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.traditionalStatement(GeneratedJavaRecognizer.java:5463)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.statement(GeneratedJavaRecognizer.java:4397)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compoundStatement(GeneratedJavaRecognizer.java:4063)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3453)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2643)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
        ... 268 more

**Comment by rnveach** [comment]
This looks to be a parsing error in the main checkstyle project and not sonar checkstyle.

I recommend to open an issue there with all the details of your config and the file that is giving the error.

**Comment by romani** [comment]
Please open issue at https://github.com/checkstyle/checkstyle

Please follow a strictly a issue format.
