### ISSUE TITLE
Cannot deactivate the plugin without uninstalling it

### ISSUE THREAD

**Issue by velicb** [checkstyle/sonar-checkstyle#405]
Sonar version: 9.1.0.47736

Checkstyle sonar plugin version: 9.3

Steps to reproduce or description of problem:

I want to "deactivate" the checkstyle plugin because it causes my sonar-scan to fail and in this paritcular case I don't need checkstyle to run in this scan. I have tried to deactivate the chekstyle rules but nevertheless it fails due to a checkstyle exception. Further I have tried to exclude the files which cause this exceptions with the "sonar.exclusions" but again it throws an exception even if the file is excluded. So is there any way (without uninstalling the plugin because I use the plugin in another case) to prevent the checkstyle plugin from stopping my scan? 

Best Regards!

**Comment by velicb** [comment]
Hi,

1: 
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Can not execute Checkstyle
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:110)
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:78)
        at org.sonar.plugins.checkstyle.CheckstyleSensor.execute(CheckstyleSensor.java:42)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:79)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:382)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:378)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:347)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /dir1/dir2/dir3/dir4/dir5/dir6/dir7/simple/src/Main.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:305)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
        at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:103)
        ... 32 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /dir1/dir2/dir3/dir4/dir5/dir6/dir7/simple/src/Main.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:152)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:331)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:292)
        ... 34 more
Caused by: java.lang.IllegalStateException: 13:8: mismatched input '@' expecting {IDENT, 'record', 'yield', 'non-sealed', 'sealed', 'permits'}
        at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:252)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
        at com.puppycrawl.tools.checkstyle.CheckstyleParserErrorStrategy.recoverInline(CheckstyleParserErrorStrategy.java:38)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.id(JavaLanguageParser.java:12132)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.qualifiedName(JavaLanguageParser.java:4468)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.packageDeclaration(JavaLanguageParser.java:464)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:384)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
        ... 38 more
Caused by: org.antlr.v4.runtime.InputMismatchException
        ... 44 more
ERROR:
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.

2. I have a Main class where I basically have a placeholder like @Variable which is changed dynamically. Which is not Java conform and due to this it throws an exception. 

3. https://community.sonarsource.com/t/all-files-are-still-parsed-by-check-style-parser-even-if-there-is-none-of-any-activated-checkstyle-rule/36801 --> If I understand you correct then the guys from Sonar are saying the opposite, that the plugin determines when it runs or not. 

Thank you in advance! 

Best Regards

**Comment by muhlba91** [comment]
can you please try adding the following filter:
- open your SQ project settings (`General Settings`)
- open `Languages` and select `Java`
- under `Checkstyle` -> `Checker Filters` add the following one:
```
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="HelloWorld\.java$"/>
</module>
```
(replace `value` with your file or an entire directory: https://checkstyle.sourceforge.io/config_filefilters.html)

**Comment by muhlba91** [comment]
closing due to inactivity.
